name: petrol_bunk_maintainence
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2

  cloud_firestore: ^4.4.0
  get: ^4.6.5
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.


  uses-material-design: true
